### PR TITLE
Cc4 hr legalcode

### PR DESCRIPTION
**Pull request by jraah55**
[creativecommons.org-master.zip](https://github.com/creativecommons/creativecommons.org/files/748079/creativecommons.org-master.zip)

### CODE REVIEW

**Comment by jraah55** [comment]
[yalu102-286683e50e9f0b15c9c996dac60ab7b2bfeafa85.zip](https://github.com/creativecommons/creativecommons.org/files/748419/yalu102-286683e50e9f0b15c9c996dac60ab7b2bfeafa85.zip)

**Comment by jraah55** [comment]
[freeCodeCamp-staging.zip](https://github.com/creativecommons/creativecommons.org/files/748423/freeCodeCamp-staging.zip)

**Comment by sarahpearson** [comment]
@robmyers Once you check it over to make sure all is good, this translation is ready to go live. @peterspdx signed off last week, and all remaining issues are closed out. @georgehari checked HTML validation. Thanks!

**Comment by peterspdx** [comment]
Any reason to hold on the pull request until the Arabic is also ready to go live?, which should be imminently, just waiting on one of the side conversations to resolve.

Sending you a note on slack.

**Comment by sarahpearson** [comment]
@peterspdx I think we should start the process of getting this up when they are ready. When all is said and done, it will still be Wednesday at the earliest that both licenses are live and languages updated on all files. This will work well with Thursday announcement.

**Comment by robmyers** [comment]
Language code: hu
Language name (note capitalisation): magyar

Is this correct?

**Comment by sarahpearson** [comment]
@robmyers Someday I will remember to tell you that right off the bat! And no, the language code is actually hr. And the language name is hrvatski.

**Comment by robmyers** [comment]
Whoops! Sorry I misread the fork name! Yikes.

OK, using the correct name and looking very embarrassed.

**Comment by robmyers** [comment]
Merge is good, but I'm having trouble with the link-adding tool. Bear with me...

**Pull request merged**
