### PR TITLE
partially fix layout / html formatting of BY*ND Dutch translations

### LINKED ISSUE #1159: CC BY-NC-ND 4.0 and CC-ND 4.0 Dutch legalcode translations have a HTML formatting mistake in Section 3(a)
## Description
CC BY-NC-ND 4.0 and CC-ND 4.0 Dutch translations have a HTML formatting mistake in Section 3(a). In English, the last parapgraph in Section 3(a)(1) follows item 3(a)(1)(C). In the Dutch translation, instead of being a tailing paragraph in 3(a)(1), it is a new item: 3(a)(2).

## Reproduction
- CC BY-NC-ND 4.0
  - English (en): [Creative Commons — Attribution-NonCommercial-NoDerivatives 4.0 International — CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.en#s3a)
  - Dutch (nl): [Creative Commons — Naamsvermelding-NietCommercieel-GeenAfgeleideWerken 4.0 Internationaal — CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.nl#s3a)
- CC BY-ND 4.0
  - English (en): [Creative Commons — Attribution-NoDerivatives 4.0 International — CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/legalcode.en#s3a)
  - Dutch (nl): [Creative Commons — Naamsvermelding-GeenAfgeleideWerken 4.0 Internationaal — CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/legalcode.nl#s3a)

## Expectation
The layout/structure of translations should match the source.

## CC BY-NC-ND 4.0 English
Screenshot showing beginning of Section 3:
cc-by-nc-nd_en

## CC BY-NC-ND 4.0 Dutch
Screenshot showing beginning of Section 3 (item 2 should be a paragraph of item 1):
cc-by-nc-nd_nl

## CC BY-ND 4.0 English
Screenshot showing beginning of Section 3:
cc-by-nd_en

## CC BY-ND 4.0 Dutch
Screenshot showing beginning of Section 3 (item 2 should be a paragraph of item 1):
cc-by-nd_nl

## Additional context
- [Legal code issues & errata - Creative Commons](https://creativecommons.org/legal-code-errata/)

## Resolution

- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by TimidRobot**
## Fixes
Fixes #1159

## Description
- fix layout / html formatting of BY*ND Dutch translations (#1159)
- correct *Technological* translation (*~~Technische =>~~ Technologische*)

## Tests
| BY* 4.0 production | BY* 4.0 testing |
| ------------------ | --------------- |
| [by-nc-nd (nl) *current*][nl-by-nc-nd-old] | [by-nc-nd (nl) *proposed*][nl-by-nc-nd-new] |
| [by-nc-sa (nl) *current*][nl-by-nc-sa-old] | [by-nc-sa (nl) *proposed*][nl-by-nc-sa-new] |
| [by-nc (nl) *current*][nl-by-nc-old] | [by-nc (nl) *proposed*][nl-by-nc-new] |
| [by-nd (nl) *current*][nl-by-nd-old] | [by-nd (nl) *proposed*][nl-by-nd-new] |
| [by-sa (nl) *current*][nl-by-sa-old] | [by-sa (nl) *proposed*][nl-by-sa-new] |
| [by (nl) *current*][nl-by-sa-old] | [by (nl) *proposed*][nl-by-sa-new] |
| [by-nc-nd (en) *current*][en-by-nc-nd-old] | |
| [by-nd (en) *current*][en-by-nd-old] | |

[nl-by-nc-nd-old]: https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.nl
[nl-by-nc-nd-new]: https://cc4-nd-nl-3-a-html-issue.legal.creativecommons.org/licenses/by-nc-nd/4.0/legalcode.nl
[nl-by-nc-sa-old]: https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.nl
[nl-by-nc-sa-new]: https://cc4-nd-nl-3-a-html-issue.legal.creativecommons.org/licenses/by-nc-sa/4.0/legalcode.nl
[nl-by-nc-old]: https://creativecommons.org/licenses/by-nc/4.0/legalcode.nl
[nl-by-nc-new]: https://cc4-nd-nl-3-a-html-issue.legal.creativecommons.org/licenses/by-nc/4.0/legalcode.nl
[nl-by-nd-old]: https://creativecommons.org/licenses/by-nd/4.0/legalcode.nl
[nl-by-nd-new]: https://cc4-nd-nl-3-a-html-issue.legal.creativecommons.org/licenses/by-nd/4.0/legalcode.nl
[nl-by-sa-old]: https://creativecommons.org/licenses/by-sa/4.0/legalcode.nl
[nl-by-sa-new]: https://cc4-nd-nl-3-a-html-issue.legal.creativecommons.org/licenses/by-sa/4.0/legalcode.nl
[nl-by-old]: https://creativecommons.org/licenses/by/4.0/legalcode.nl
[nl-by-new]: https://cc4-nd-nl-3-a-html-issue.legal.creativecommons.org/licenses/by/4.0/legalcode.nl
[en-by-nc-nd-old]: https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.en
[en-by-nd-old]: https://creativecommons.org/licenses/by-nd/4.0/legalcode.en

### Current
Screen Shot 2020-09-24 at 09 14 59

### Proposed
Screen Shot 2020-09-24 at 09 14 51

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarahpearson** [comment]
@mzeinstra Can you take a look at this to make sure it is okay?

**Comment by mzeinstra** [comment]
@TimidRobot @sarahpearson Yes this is a good fix, to bad that we didn't see this sooner. Thanks for spotting it!

**Comment by sarahpearson** [comment]
@TimidRobot here is the translated language from the team: 

Een fout in deze vertaling is aangepast op [NUMERICAL DATE].

One wrinkle is that we have one other small correction pending in the Dutch files. The diff is here: https://github.com/creativecommons/creativecommons.org/compare/cc4-nl-legalcode. 

Can we include both of these corrections in this update @TimidRobot?

**Review by sarahpearson — APPROVED** [review]
Looks good. Thank you!

**Comment by Swansoppia** [comment]
> ## Fixes
> Fixes #1159
> 
> ## Description
> * fix layout / html formatting of BY*ND Dutch translations ([CC BY-NC-ND 4.0 and CC-ND 4.0 Dutch legalcode translations have a HTML formatting mistake in Section 3(a) #1159](https://github.com/creativecommons/creativecommons.org/issues/1159))
> * correct _Technological_ translation (_~Technische =>~ Technologische_)
> 
> ## Technical details
> ## Tests
> BY* 4.0 production	BY* 4.0 testing
> [by-nc-nd (nl) _current_](https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.nl)	[by-nc-nd (nl) _proposed_](https://cc4-nd-nl-3-a-html-issue.legal.creativecommons.org/licenses/by-nc-nd/4.0/legalcode.nl)
> [by-nc-sa (nl) _current_](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.nl)	[by-nc-sa (nl) _proposed_](https://cc4-nd-nl-3-a-html-issue.legal.creativecommons.org/licenses/by-nc-sa/4.0/legalcode.nl)
> [by-nc (nl) _current_](https://creativecommons.org/licenses/by-nc/4.0/legalcode.nl)	[by-nc (nl) _proposed_](https://cc4-nd-nl-3-a-html-issue.legal.creativecommons.org/licenses/by-nc/4.0/legalcode.nl)
> [by-nd (nl) _current_](https://creativecommons.org/licenses/by-nd/4.0/legalcode.nl)	[by-nd (nl) _proposed_](https://cc4-nd-nl-3-a-html-issue.legal.creativecommons.org/licenses/by-nd/4.0/legalcode.nl)
> [by-sa (nl) _current_](https://creativecommons.org/licenses/by-sa/4.0/legalcode.nl)	[by-sa (nl) _proposed_](https://cc4-nd-nl-3-a-html-issue.legal.creativecommons.org/licenses/by-sa/4.0/legalcode.nl)
> [by (nl) _current_](https://creativecommons.org/licenses/by-sa/4.0/legalcode.nl)	[by (nl) _proposed_](https://cc4-nd-nl-3-a-html-issue.legal.creativecommons.org/licenses/by-sa/4.0/legalcode.nl)
> [by-nc-nd (en) _current_](https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.en)	
> [by-nd (en) _current_](https://creativecommons.org/licenses/by-nd/4.0/legalcode.en)	
> ## Screenshots
> ### Current
> Screen Shot 2020-09-24 at 09 14 59
> 
> ### Proposed
> Screen Shot 2020-09-24 at 09 14 51
> 
> ## Checklist
> * [x]  My pull request has a descriptive title (not a vague title like `Update index.md`).
> * [x]  My pull request targets the _default_ branch of the repository (`main` or `master`).
> * [x]  My commit messages follow [best practices](https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53).
> * [x]  My code follows the established code style of the repository.
> * [ ]  I added tests for the changes I made (if applicable).
> * [ ]  I added or updated documentation (if applicable).
> * [x]  I tried running the project locally and verified that there are no
>   visible errors.
> 
> ## Developer Certificate of Origin
> Developer Certificate of Origin

**Pull request merged**
