### PR TITLE
Correct Portuguese BY-SA definitions formatting

### LINKED ISSUE #1153: BY-SA 4.0 pt has one more definition than BY-SA 4.0 en
## Description
BY-SA 4.0 pt has one more definition than BY-SA 4.0 en

This issue was reported by @dpoirier

## Reproduction

- https://creativecommons.org/licenses/by-sa/4.0/legalcode.en
  - 1.m:
    Screen Shot 2020-08-25 at 14 16 16
- https://creativecommons.org/licenses/by-sa/4.0/legalcode.pt
  - 1.m & 1.n:
    Screen Shot 2020-08-25 at 14 16 25

## Additional context
All of the Portuguese BY* 4.0 translations are consistent, with the exception of BY-SA:
1. `docroot/legalcode/by-nc-nd_4.0_pt.html`: [Line 208](https://github.com/creativecommons/creativecommons.org/blob/9ab7979b86397d51beefa46eb3a9742f2cdda421/docroot/legalcode/by-nc-nd_4.0_pt.html#L208)
    ```html
    <li id="s1k"><strong>Você</strong> significa o indivíduo ou entidade que exerce os Direitos Licenciados sob esta Licença Pública. <strong>Lhe</strong>, <strong>Seu</strong>, <strong>Sua</strong> e <strong>Suas</strong> têm um significado correspondente.</li>
    ```
1. `docroot/legalcode/by-nc-sa_4.0_pt.html`: [Line 211](https://github.com/creativecommons/creativecommons.org/blob/9ab7979b86397d51beefa46eb3a9742f2cdda421/docroot/legalcode/by-nc-sa_4.0_pt.html#L211)
    ```html
    <li id="s1n"><strong>Você</strong> significa o indivíduo ou entidade que exerce os Direitos Licenciados sob esta Licença Pública. <strong>Lhe</strong>, <strong>Seu</strong>, <strong>Sua</strong> e <strong>Suas</strong> têm um significado correspondente.</li>
    ```
1. `docroot/legalcode/by-nc_4.0_pt.html`: [Line 209](https://github.com/creativecommons/creativecommons.org/blob/9ab7979b86397d51beefa46eb3a9742f2cdda421/docroot/legalcode/by-nc_4.0_pt.html#L209)
    ```html
    <li id="s1l"><strong>Você</strong> significa o indivíduo ou entidade que exerce os Direitos Licenciados sob esta Licença Pública. <strong>Lhe</strong>, <strong>Seu</strong>, <strong>Sua</strong> e <strong>Suas</strong> têm um significado correspondente.</li>
    ```
1. `docroot/legalcode/by-nd_4.0_pt.html`: [Line 207](https://github.com/creativecommons/creativecommons.org/blob/9ab7979b86397d51beefa46eb3a9742f2cdda421/docroot/legalcode/by-nd_4.0_pt.html#L207)
    ```html
    <li id="s1j"><strong>Você</strong> significa o indivíduo ou entidade que exerce os Direitos Licenciados sob esta Licença Pública. <strong>Lhe</strong>, <strong>Seu</strong>, <strong>Sua</strong> e <strong>Suas</strong> têm um significado correspondente.</li>
    ```
1. :warning: **`docroot/legalcode/by-sa_4.0_pt.html`: [Lines 210-211](https://github.com/creativecommons/creativecommons.org/blob/9ab7979b86397d51beefa46eb3a9742f2cdda421/docroot/legalcode/by-sa_4.0_pt.html#L210-L211)**
    ```html
    <li id="s1m"><strong>Você</strong> significa o indivíduo ou entidade que exerce os Direitos Licenciados sob esta Licença Pública.</li>
    <li id="s1n"><strong>Lhe</strong>, <strong>Seu</strong>, <strong>Sua</strong> e <strong>Suas</strong> têm um significado correspondente.</li>
    ```
1. `docroot/legalcode/by_4.0_pt.html`: [Line 208](https://github.com/creativecommons/creativecommons.org/blob/9ab7979b86397d51beefa46eb3a9742f2cdda421/docroot/legalcode/by_4.0_pt.html#L208)
    ```html
    <li id="s1k"><strong>Você</strong> significa o indivíduo ou entidade que exerce os Direitos Licenciados sob esta Licença Pública. <strong>Lhe</strong>, <strong>Seu</strong>, <strong>Sua</strong> e <strong>Suas</strong> têm um significado correspondente.</li>
    ```

## Resolution

- [ ] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by TimidRobot**
## Fixes
Fixes #1153

## Description
Correct Portuguese BY-SA definitions formatting

### Tests

| BY* 4.0 production | BY* 4.0 testing |
| ------------------ | --------------- |
| [by-sa (pt) *old*][pt-by-sa-old] | [by-sa (pt) *new*][pt-by-sa-new] |
| [by-sa (en) *old*][en-by-sa-old] | [by-sa (en) *new*][en-by-sa-new] |

[pt-by-sa-old]: https://creativecommons.org/licenses/by-sa/4.0/legalcode.pt
[pt-by-sa-new]: https://by-sa-4-0-pt-definitions.legal.creativecommons.org/licenses/by-sa/4.0/legalcode.pt
[en-by-sa-old]: https://creativecommons.org/licenses/by-sa/4.0/legalcode.en
[en-by-sa-new]: https://by-sa-4-0-pt-definitions.legal.creativecommons.org/licenses/by-sa/4.0/legalcode.en

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- N/A I added tests for the changes I made (if applicable).
- N/A I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by georgehari — APPROVED** [review]
It's OK.

**Comment by sarahpearson** [comment]
Approved by the translation team!

**Comment by sarahpearson** [comment]
Thanks! I updated the errata page: https://creativecommons.org/legal-code-errata/

**Comment by sarahpearson** [comment]
@TimidRobot here is the language from the translation team to add to the header at the top of the legal code:

Em 8 de Setembro de 2020 foi corrigido um erro nesta tradução. 

Thank you!

**Pull request merged**
